version: '3'

services:
  gocrud:
    image: gocrud:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOCRUD_MONGO_URI=mongodb://mongodb:27017 # Overwrite default MongoDB URL

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"